# Bug:
#  Custom generators doesn't work on server-side
#
# Tracker:
#  https://github.com/null2264/CobbleGen/issues/91
#
# Status:
#  Investigating

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      NEOFORGE_VERSION: "21.1.206"
      MODS: |
        https://cdn.modrinth.com/data/qRogT5Gy/versions/FB4QjG7i/cobblegen-5.4.6%2B1.21.1b1222-BETA-neoforge.jar
      ONLINE_MODE: "FALSE"
    volumes:
      - ./neo-data:/data:Z
