modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/null2264/CobbleGen/issues"

[[mods]]
modId = "cobblegen"
version = "${version}"
displayName = "CobbleGen"
displayURL = "https://github.com/null2264/CobbleGen"
logoFile = "icon.png"
authors = "null2264"
description = "An MC mod that allows you to customize cobblestone (stone and basalt) generators"

[[mixins]]
config = "cobblegen.mixins.json"

[[dependencies.cobblegen]]
modId = "${forge}"
# This changed to 'type = "required"' in NeoForge 1.20.4 and newer
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblegen]]
modId = "minecraft"
# This changed to 'type = "required"' in NeoForge 1.20.4 and newer
mandatory = true
versionRange = "${mcversion}"
ordering = "NONE"
side = "BOTH"

[mc-publish]
modrinth = "qRogT5Gy"
curseforge = 581293
#>>loaders = ["forge"]
#==loaders = ["forge", "neoforge"]
#<<loaders = ["neoforge"]
