name: build
on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@f796b7ea8b1d0ac9eefb3b69aa3500078a6a753e
        with:
          java: 21
          gradle-home-cache-includes: |
            caches
            notifications
            Kits/.gradle/caches
            Kits/.gradle/notifications
          gradle-cache-if: true  # FIXME: For debugging, for prod use expression

      - name: Setup NeoForge Kits for snapshots
        uses: null2264/actions/neoforge-snapshot@f796b7ea8b1d0ac9eefb3b69aa3500078a6a753e
        with:
          mc-version: 24w14a
          skip-gradle-setup: 'true'

      - name: Get mod versions
        id: get-mod-versions
        run: |
          echo "versions=$(ls versions | grep -e '.\.' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        uses: null2264/actions/replaymod-preprocessor-compile@f796b7ea8b1d0ac9eefb3b69aa3500078a6a753e
        with:
          versions: ${{ steps.get-mod-versions.outputs.versions }}

      - name: Archive build results
        run: tar -I zstd -cf build.tar.zst versions/*/build/libs

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build.tar.zst
          if-no-files-found: error
          retention-days: 3
