name: build
on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Archive build results
        run: tar -I zstd -cf build.tar.zst versions/*/build/libs
      - name: Upload build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build.tar.zst
          if-no-files-found: error
          retention-days: 3
