name: build
on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: null2264/actions/gradle-setup@d458cba90251e858b20fe655d89ff78626318b0c
        with:
          java: 21
      - uses: null2264/actions/neoforge-snapshot@d458cba90251e858b20fe655d89ff78626318b0c
        with:
          mc-version: 24w14a
          java-version: 21
      - name: Get mod versions
        id: get-mod-versions
        run: |
          echo "versions=$(ls versions | grep -e '.\.' | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - uses: null2264/actions/replaymod-preprocessor-compile@d458cba90251e858b20fe655d89ff78626318b0c
        with:
          versions: ${{ steps.get-mod-versions.outputs.versions }}
      - name: Archive build results
        run: tar -I zstd -cf build.tar.zst versions/*/build/libs
      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build.tar.zst
          if-no-files-found: error
          retention-days: 3
