name: build
on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: null2264/actions/gradle-setup@ea3bc4a5b4ab11bf1a02ce4bbb32aa6c829fed44
        with:
          java: 21
      - uses: null2264/actions/neoforge-snapshot@ea3bc4a5b4ab11bf1a02ce4bbb32aa6c829fed44
        with:
          mc-version: 24w14a
      - name: Setup build environment
        run: |
          chmod +x ./gradlew
          echo "org.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_17_X64,JAVA_HOME_21_X64" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx6G" >> gradle.properties
          echo "org.gradle.cache.cleanup=false" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./.scripts/compile.sh
      - name: Archive build results
        run: tar -I zstd -cf build.tar.zst versions/*/build/libs
      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build.tar.zst
          if-no-files-found: error
          retention-days: 3
