name: release
on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - run: chmod +x ./gradlew
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Archive build results
        run: tar -I zstd -cf build.tar.zst versions/*/build/libs
      - name: Upload build and gradle folders
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build.tar.zst
          if-no-files-found: error
          retention-days: 3
      - name: Upload to CurseForge and Modrinth
        run: ./gradlew publishMods --stacktrace --no-daemon --max-workers 1
        env:
          CHANGELOG: ${{ github.event.release.body }}
          CURSEFORGE: ${{ secrets.CURSEFORGE }}
          MODRINTH: ${{ secrets.MODRINTH }}

  upload-release-artifacts:
    name: Upload Release Artifacts
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Unpack build artifact
        run: tar axf build.tar.zst
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            versions/*/build/libs/!(*-dev-shade|*-sources).jar
